import { Recipe } from '@/types';

export const RECIPES_DATA: Recipe[] = [
  {
    id: 'rec-paneer-tomato-bhurji',
    slug: 'paneer-tomato-bhurji',
    name: 'Homestyle Paneer Tomato Bhurji',
    description: 'Scrambled fresh paneer tossed with ripe juicy tomatoes, cumin, and mild spices.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
    timeMinutes: 15,
    difficulty: 'Easy',
    servings: 2,
    category: 'Quick Meal',
    isVegetarian: true,
    tags: ['Quick', 'Under 20 min', 'High Protein', 'Vegetarian'],
    ingredients: [
      { name: 'Paneer', amount: '200g' },
      { name: 'Tomato', amount: '2 pcs' },
      { name: 'Onion', amount: '1 medium' },
      { name: 'Cooking oil', amount: '1 tbsp' },
      { name: 'Salt', amount: 'to taste' },
    ],
    steps: [
      'Crumble fresh paneer into coarse bits using your hands.',
      'Heat oil in a pan, add chopped onion and sauté until lightly browned.',
      'Add chopped tomatoes and cook for 3 minutes until soft and juicy.',
      'Fold in crumbled paneer and salt. Toss well on medium heat for 2 minutes. Serve hot.',
    ],
  },
  {
    id: 'rec-creamy-tomato-soup',
    slug: 'creamy-tomato-soup',
    name: 'Creamy Tomato & Milk Soup',
    description: 'Rich and comforting tomato soup smoothed with fresh milk and roasted garlic.',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80',
    timeMinutes: 15,
    difficulty: 'Easy',
    servings: 2,
    category: 'Soup',
    isVegetarian: true,
    tags: ['Comfort', 'Under 20 min', 'Vegetarian', 'Warm'],
    ingredients: [
      { name: 'Tomato', amount: '3 ripe' },
      { name: 'Milk', amount: '200 ml' },
      { name: 'Garlic', amount: '2 cloves' },
      { name: 'Salt', amount: '1/2 tsp' },
      { name: 'Black pepper', amount: '1/4 tsp' },
    ],
    steps: [
      'Dice tomatoes and sauté with minced garlic until thoroughly collapsed and pulpy.',
      'Blend the tomato mixture into a smooth puree and return to the saucepan.',
      'Lower the heat and slowly stir in the milk, salt, and black pepper.',
      'Simmer gently without boiling for 3 minutes and serve warm.',
    ],
  },
  {
    id: 'rec-palak-paneer',
    slug: 'palak-paneer',
    name: 'Palak Paneer',
    description: 'Fresh cottage cheese cubes simmered in a smooth, fragrant spiced spinach puree with garlic and cumin.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
    timeMinutes: 25,
    difficulty: 'Easy',
    servings: 3,
    category: 'Main Course',
    isVegetarian: true,
    tags: ['Vegetarian', 'Under 30 min', 'Uses what I have', 'Quick'],
    ingredients: [
      { name: 'Spinach', amount: '250g' },
      { name: 'Paneer', amount: '200g' },
      { name: 'Onion', amount: '1 medium' },
      { name: 'Tomato', amount: '1 medium' },
      { name: 'Garlic', amount: '4 cloves' },
      { name: 'Ginger', amount: '1 inch piece' },
      { name: 'Cumin seeds', amount: '1 tsp' },
      { name: 'Garam masala', amount: '1/2 tsp' },
      { name: 'Cooking oil', amount: '1 tbsp' },
      { name: 'Salt', amount: 'to taste' },
    ],
    steps: [
      'Blanch the fresh spinach in boiling water for 2 minutes, then plunge immediately into cold water to preserve the vibrant green color.',
      'Blend the blanched spinach with ginger and garlic into a smooth puree.',
      'Heat oil in a pan, crackle cumin seeds, then add finely chopped onions and sauté until translucent.',
      'Add chopped tomato and cook until soft and oil begins to separate.',
      'Pour in the spinach puree, add salt and garam masala, and simmer gently on low heat for 4-5 minutes.',
      'Gently fold in fresh paneer cubes and let them absorb the flavors for 2 minutes. Serve warm with roti or rice.',
    ],
  },
  {
    id: 'rec-tomato-pasta',
    slug: 'tomato-pasta',
    name: 'Rustic Garlic & Tomato Pasta',
    description: 'Al dente pasta tossed in a rich, slow-simmered fresh tomato reduction infused with garlic and olive oil.',
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80',
    timeMinutes: 20,
    difficulty: 'Easy',
    servings: 2,
    category: 'Pasta',
    isVegetarian: true,
    tags: ['Quick', 'Under 30 min', 'Vegetarian', 'Uses what I have'],
    ingredients: [
      { name: 'Pasta', amount: '200g' },
      { name: 'Tomatoes', amount: '4 ripe' },
      { name: 'Garlic', amount: '4 cloves' },
      { name: 'Olive oil', amount: '2 tbsp' },
      { name: 'Salt', amount: '1 tsp' },
      { name: 'Black pepper', amount: '1/2 tsp' },
      { name: 'Herbs or Basil', amount: '1 tsp' },
    ],
    steps: [
      'Bring a large pot of salted water to a rolling boil and cook pasta until al dente.',
      'Finely dice the ripe tomatoes and slice the garlic thinly.',
      'Heat olive oil in a wide skillet over medium-low heat. Add garlic and sauté gently until fragrant and lightly golden.',
      'Add the chopped tomatoes, salt, and pepper. Crush tomatoes lightly with a wooden spoon and simmer for 10 minutes until a rich sauce forms.',
      'Transfer the cooked pasta directly into the sauce with a splash of starchy pasta water. Toss vigorously to emulsify.',
      'Finish with fresh herbs or black pepper and serve immediately.',
    ],
  },
  {
    id: 'rec-veg-fried-rice',
    slug: 'vegetable-fried-rice',
    name: 'Vegetable Fried Rice',
    description: 'High-heat wok-tossed cooked rice with crispy diced vegetables, aromatics, and savoury seasoning.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
    timeMinutes: 15,
    difficulty: 'Easy',
    servings: 2,
    category: 'Rice',
    isVegetarian: true,
    tags: ['Quick', 'Under 30 min', 'Uses what I have', 'Vegetarian'],
    ingredients: [
      { name: 'Rice', amount: '2 cups cooked' },
      { name: 'Carrots', amount: '1 medium' },
      { name: 'Onion', amount: '1 small' },
      { name: 'Bell pepper', amount: '1/2' },
      { name: 'Garlic', amount: '3 cloves' },
      { name: 'Soy sauce', amount: '1.5 tbsp' },
      { name: 'Cooking oil', amount: '1.5 tbsp' },
      { name: 'Black pepper', amount: 'to taste' },
    ],
    steps: [
      'Use cooled or day-old cooked rice for the best grains and texture.',
      'Heat oil in a wok or heavy skillet until smoking hot. Add minced garlic and diced onions, tossing briskly for 30 seconds.',
      'Add diced carrots and bell peppers; stir-fry on high heat for 2 minutes so they stay crisp-tender.',
      'Add the rice, breaking up any clumps with the back of the spatula.',
      'Drizzle soy sauce around the rim of the wok and season with freshly cracked black pepper.',
      'Toss everything continuously over high heat for 2 minutes until hot and well combined.',
    ],
  },
  {
    id: 'rec-aloo-gobi',
    slug: 'aloo-gobi',
    name: 'Homestyle Aloo Gobi',
    description: 'A comforting dry curry of tender potatoes and cauliflower florets roasted with turmeric, cumin, and ginger.',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
    timeMinutes: 30,
    difficulty: 'Medium',
    servings: 4,
    category: 'Main Course',
    isVegetarian: true,
    tags: ['Vegetarian', 'Under 30 min', 'Uses what I have'],
    ingredients: [
      { name: 'Potatoes', amount: '2 medium' },
      { name: 'Cauliflower', amount: '1 small head' },
      { name: 'Onion', amount: '1 medium' },
      { name: 'Tomato', amount: '1 medium' },
      { name: 'Ginger', amount: '1 tbsp grated' },
      { name: 'Turmeric powder', amount: '1/2 tsp' },
      { name: 'Cumin seeds', amount: '1 tsp' },
      { name: 'Coriander powder', amount: '1 tsp' },
      { name: 'Oil', amount: '2 tbsp' },
      { name: 'Salt', amount: 'to taste' },
    ],
    steps: [
      'Cut potatoes into bite-sized cubes and cauliflower into medium florets. Rinse and pat dry.',
      'Heat oil in a heavy-bottom pan. Add cumin seeds and let them sizzle.',
      'Add chopped onions and ginger, sautéing until golden brown.',
      'Add turmeric, coriander powder, and diced tomatoes. Cook until soft.',
      'Add the potatoes and cauliflower, tossing well to coat with spices.',
      'Cover with a lid and cook on low heat for 15-18 minutes, stirring occasionally until vegetables are fork-tender. Garnish with coriander.',
    ],
  },
  {
    id: 'rec-paneer-bhurji',
    slug: 'paneer-bhurji',
    name: 'Spiced Paneer Bhurji',
    description: 'Quick scrambled cottage cheese cooked with caramelised onions, juicy tomatoes, green chillies, and warm spices.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80',
    timeMinutes: 15,
    difficulty: 'Easy',
    servings: 2,
    category: 'Breakfast / Quick Meal',
    isVegetarian: true,
    tags: ['Quick', 'Under 30 min', 'Vegetarian', 'Uses what I have'],
    ingredients: [
      { name: 'Paneer', amount: '200g crumbled' },
      { name: 'Onion', amount: '1 large' },
      { name: 'Tomato', amount: '1 large' },
      { name: 'Ginger', amount: '1 tsp grated' },
      { name: 'Turmeric powder', amount: '1/4 tsp' },
      { name: 'Garam masala', amount: '1/2 tsp' },
      { name: 'Butter or Oil', amount: '1.5 tbsp' },
      { name: 'Salt', amount: 'to taste' },
    ],
    steps: [
      'Crumble fresh paneer with your fingers into coarse pieces.',
      'Melt butter or heat oil in a skillet. Add chopped onions and ginger, sautéing until lightly browned.',
      'Add diced tomatoes, turmeric, and salt. Cook until tomatoes turn mushy.',
      'Add the crumbled paneer and garam masala. Toss quickly on medium heat for 2-3 minutes.',
      'Do not overcook to keep the paneer soft and juicy. Serve immediately with warm toast or rotis.',
    ],
  },
  {
    id: 'rec-spinach-dal',
    slug: 'spinach-dal',
    name: 'Dal Palak (Spinach Dal)',
    description: 'Hearty yellow lentils simmered with chopped tender spinach leaves and tempered with garlic and cumin.',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80',
    timeMinutes: 25,
    difficulty: 'Easy',
    servings: 4,
    category: 'Main Course',
    isVegetarian: true,
    tags: ['Under 30 min', 'Vegetarian', 'Uses what I have', 'Quick'],
    ingredients: [
      { name: 'Dal', amount: '1 cup yellow lentils' },
      { name: 'Spinach', amount: '150g chopped' },
      { name: 'Onion', amount: '1 small' },
      { name: 'Tomato', amount: '1 small' },
      { name: 'Garlic', amount: '5 cloves sliced' },
      { name: 'Cumin seeds', amount: '1 tsp' },
      { name: 'Turmeric powder', amount: '1/2 tsp' },
      { name: 'Ghee or Oil', amount: '1.5 tbsp' },
      { name: 'Salt', amount: 'to taste' },
    ],
    steps: [
      'Rinse lentils and pressure cook or boil with water, turmeric, and salt until completely soft.',
      'In a separate pan, heat ghee or oil. Crackle cumin seeds and fry garlic slices until golden and aromatic.',
      'Add finely chopped onion and tomato, cooking for 3 minutes.',
      'Add the chopped spinach and cook down for 2 minutes until wilted.',
      'Pour in the cooked dal, stir well, and adjust consistency with water if needed. Simmer for 4 minutes.',
      'Adjust seasoning and serve hot with steamed rice or flatbread.',
    ],
  },
  {
    id: 'rec-masala-omelette',
    slug: 'masala-omelette',
    name: 'Fluffy Masala Omelette',
    description: 'Golden, protein-rich pan-folded eggs with chopped tomatoes, onions, herbs, and mild spices.',
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80',
    timeMinutes: 10,
    difficulty: 'Easy',
    servings: 1,
    category: 'Breakfast',
    isVegetarian: false,
    tags: ['Quick', 'Under 30 min', 'Uses what I have'],
    ingredients: [
      { name: 'Eggs', amount: '2 large' },
      { name: 'Onion', amount: '2 tbsp finely chopped' },
      { name: 'Tomatoes', amount: '2 tbsp finely chopped' },
      { name: 'Milk', amount: '1 tbsp' },
      { name: 'Butter', amount: '1 tsp' },
      { name: 'Salt', amount: '1/4 tsp' },
      { name: 'Black pepper', amount: '1/4 tsp' },
    ],
    steps: [
      'Whisk eggs in a bowl with milk, salt, and pepper until light and slightly frothy.',
      'Fold in finely diced onions and tomatoes.',
      'Melt butter in a non-stick pan over medium heat.',
      'Pour egg mixture, tilting pan to cover the surface evenly. Cook for 2 minutes until bottom sets.',
      'Carefully fold in half and slide onto a plate. Enjoy hot.',
    ],
  },
  {
    id: 'rec-creamy-tomato-soup',
    slug: 'creamy-tomato-soup',
    name: 'Silky Tomato & Herb Soup',
    description: 'Smooth roasted tomato soup with a splash of milk or cream, garlic, and cracked pepper.',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80',
    timeMinutes: 20,
    difficulty: 'Easy',
    servings: 2,
    category: 'Soup',
    isVegetarian: true,
    tags: ['Quick', 'Under 30 min', 'Vegetarian', 'Uses what I have'],
    ingredients: [
      { name: 'Tomatoes', amount: '4 ripe' },
      { name: 'Milk', amount: '1/2 cup' },
      { name: 'Garlic', amount: '3 cloves' },
      { name: 'Butter', amount: '1 tbsp' },
      { name: 'Salt', amount: '1/2 tsp' },
      { name: 'Black pepper', amount: '1/4 tsp' },
    ],
    steps: [
      'Coarsely chop tomatoes. Sauté garlic in butter until fragrant.',
      'Add tomatoes and salt, cooking covered on medium heat for 10 minutes.',
      'Blend the tomato mixture until completely smooth and pass through a sieve if desired.',
      'Return to low heat, whisk in milk gently to prevent curdling, and season with black pepper.',
      'Serve warm with toasted bread.',
    ],
  },
];
