import { FoodLibraryItem } from '@/types';

export const FOOD_LIBRARY_CATALOG: FoodLibraryItem[] = [
  // ==========================================
  // PRODUCE — VEGETABLES
  // ==========================================
  {
    id: 'food-tomato',
    name: 'Tomatoes',
    normalizedName: 'tomato',
    aliases: ['tamatar', 'vine tomatoes', 'fresh tomato', 'desi tomato', 'roma tomato'],
    category: 'Produce',
    subcategory: 'Vegetables',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg', 'pcs'],
    storageType: 'refrigerator',
    perishability: 'high',
    typicalShelfLifeDays: 7,
    tags: ['vegetable', 'curry-base', 'staple', 'indian'],
    commonUses: ['Dal Tadka', 'Tomato Chutney', 'Curry Base', 'Fresh Salads'],
  },
  {
    id: 'food-cherry-tomato',
    name: 'Cherry Tomatoes',
    normalizedName: 'cherry tomato',
    aliases: ['baby tomato', 'grape tomatoes', 'cherry tamatar', 'sweet tomatoes'],
    category: 'Produce',
    subcategory: 'Vegetables',
    defaultUnit: 'g',
    commonUnits: ['g', 'pack'],
    storageType: 'refrigerator',
    perishability: 'high',
    typicalShelfLifeDays: 8,
    tags: ['vegetable', 'salad', 'roasting', 'snack'],
    commonUses: ['Pasta Salads', 'Sheet Pan Bakes', 'Fresh Bowls', 'Snacking'],
  },
  {
    id: 'food-tomato-puree',
    name: 'Tomato Puree / Paste',
    normalizedName: 'tomato puree',
    aliases: ['canned tomato', 'tomato paste', 'passata', 'crushed tomato', 'pureed tomato'],
    category: 'Pantry Staples',
    subcategory: 'Canned Goods',
    defaultUnit: 'g',
    commonUnits: ['g', 'pack', 'can'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 90,
    tags: ['canned', 'curry-base', 'pasta-sauce'],
    commonUses: ['Makhani Gravy', 'Pasta Marinara', 'Quick Shakshuka', 'Stew Base'],
  },
  {
    id: 'food-onion',
    name: 'Red Onions',
    normalizedName: 'red onion',
    aliases: ['onion', 'pyaz', 'kanda', 'onions', 'shallots'],
    category: 'Produce',
    subcategory: 'Vegetables',
    defaultUnit: 'kg',
    commonUnits: ['kg', 'g', 'pcs'],
    storageType: 'pantry',
    perishability: 'medium',
    typicalShelfLifeDays: 21,
    tags: ['vegetable', 'curry-base', 'staple', 'indian'],
    commonUses: ['Tadka & Base Gravy', 'Kachumber Salad', 'Poha / Upma', 'Biryani'],
  },
  {
    id: 'food-potato',
    name: 'Potatoes',
    normalizedName: 'potato',
    aliases: ['aloo', 'batata', 'potatoes', 'pahadi aloo', 'baby potatoes'],
    category: 'Produce',
    subcategory: 'Vegetables',
    defaultUnit: 'kg',
    commonUnits: ['kg', 'g', 'pcs'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 25,
    tags: ['vegetable', 'staple', 'tuber'],
    commonUses: ['Aloo Gobi', 'Jeera Aloo', 'Aloo Paratha', 'Roast Potatoes'],
  },
  {
    id: 'food-ginger',
    name: 'Fresh Ginger',
    normalizedName: 'ginger',
    aliases: ['adrak', 'fresh adrak', 'ginger root'],
    category: 'Produce',
    subcategory: 'Vegetables',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg', 'pcs'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 21,
    tags: ['spice', 'aromatic', 'tea', 'curry-base'],
    commonUses: ['Ginger Chai', 'Ginger Garlic Paste', 'Stir-fry', 'Ayurvedic Kadha'],
  },
  {
    id: 'food-garlic',
    name: 'Garlic Bulbs',
    normalizedName: 'garlic',
    aliases: ['lahsun', 'garlic cloves', 'garlic pod', 'lasun'],
    category: 'Produce',
    subcategory: 'Vegetables',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg', 'pcs'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 30,
    tags: ['aromatic', 'staple', 'curry-base'],
    commonUses: ['Garlic Tadka', 'Garlic Naan / Toast', 'Pasta Aglio e Olio', 'Rasam'],
  },
  {
    id: 'food-green-chilli',
    name: 'Green Chillies',
    normalizedName: 'green chilli',
    aliases: ['hari mirch', 'green peppers', 'chilli', 'mirchi', 'spicy chilli'],
    category: 'Produce',
    subcategory: 'Vegetables',
    defaultUnit: 'g',
    commonUnits: ['g', 'pcs'],
    storageType: 'refrigerator',
    perishability: 'high',
    typicalShelfLifeDays: 10,
    tags: ['spice', 'staple', 'tadka'],
  },
  {
    id: 'food-cauliflower',
    name: 'Cauliflower',
    normalizedName: 'cauliflower',
    aliases: ['gobhi', 'gobi', 'phool gobi'],
    category: 'Produce',
    subcategory: 'Vegetables',
    defaultUnit: 'pcs',
    commonUnits: ['pcs', 'g', 'kg'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 7,
    tags: ['vegetable', 'subzi'],
  },
  {
    id: 'food-cabbage',
    name: 'Green Cabbage',
    normalizedName: 'cabbage',
    aliases: ['patta gobhi', 'bandh gobi', 'cabbage head'],
    category: 'Produce',
    subcategory: 'Vegetables',
    defaultUnit: 'pcs',
    commonUnits: ['pcs', 'g', 'kg'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 14,
    tags: ['vegetable', 'salad'],
  },
  {
    id: 'food-capsicum-green',
    name: 'Green Capsicum',
    normalizedName: 'green capsicum',
    aliases: ['shimla mirch', 'bell pepper', 'green bell pepper', 'capsicum'],
    category: 'Produce',
    subcategory: 'Vegetables',
    defaultUnit: 'pcs',
    commonUnits: ['pcs', 'g', 'kg'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 8,
    tags: ['vegetable', 'stir-fry'],
  },
  {
    id: 'food-capsicum-red-yellow',
    name: 'Coloured Bell Peppers',
    normalizedName: 'bell pepper',
    aliases: ['red capsicum', 'yellow capsicum', 'red bell pepper', 'yellow bell pepper'],
    category: 'Produce',
    subcategory: 'Vegetables',
    defaultUnit: 'pcs',
    commonUnits: ['pcs', 'g'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 8,
    tags: ['vegetable', 'salad', 'stir-fry'],
  },
  {
    id: 'food-carrots',
    name: 'Fresh Carrots',
    normalizedName: 'carrot',
    aliases: ['gajar', 'red carrot', 'orange carrot', 'carrots'],
    category: 'Produce',
    subcategory: 'Vegetables',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg', 'pcs'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 14,
    tags: ['vegetable', 'salad', 'subzi'],
  },
  {
    id: 'food-peas',
    name: 'Fresh Green Peas',
    normalizedName: 'green pea',
    aliases: ['matar', 'hari matar', 'peas', 'fresh matar'],
    category: 'Produce',
    subcategory: 'Vegetables',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 6,
    tags: ['vegetable', 'curry'],
  },
  {
    id: 'food-cucumber',
    name: 'Cucumber',
    normalizedName: 'cucumber',
    aliases: ['kheera', 'kakdi', 'english cucumber', 'cucumbers'],
    category: 'Produce',
    subcategory: 'Vegetables',
    defaultUnit: 'pcs',
    commonUnits: ['pcs', 'g', 'kg'],
    storageType: 'refrigerator',
    perishability: 'high',
    typicalShelfLifeDays: 6,
    tags: ['salad', 'hydrating'],
  },
  {
    id: 'food-lemon',
    name: 'Fresh Lemons',
    normalizedName: 'lemon',
    aliases: ['nimbu', 'lime', 'yellow lemon', 'fresh lime'],
    category: 'Produce',
    subcategory: 'Vegetables',
    defaultUnit: 'pcs',
    commonUnits: ['pcs', 'pack'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 14,
    tags: ['citrus', 'seasoning', 'salad'],
  },
  {
    id: 'food-okra',
    name: 'Lady Finger (Okra)',
    normalizedName: 'okra',
    aliases: ['bhindi', 'okra', 'ladyfinger', 'tender bhindi'],
    category: 'Produce',
    subcategory: 'Vegetables',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg'],
    storageType: 'refrigerator',
    perishability: 'high',
    typicalShelfLifeDays: 5,
    tags: ['vegetable', 'subzi', 'indian'],
  },
  {
    id: 'food-eggplant',
    name: 'Eggplant (Baingan)',
    normalizedName: 'eggplant',
    aliases: ['baingan', 'brinjal', 'aubergine', 'bharta baingan', 'purple brinjal'],
    category: 'Produce',
    subcategory: 'Vegetables',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg', 'pcs'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 7,
    tags: ['vegetable', 'curry'],
  },
  {
    id: 'food-small-brinjal',
    name: 'Small Round Brinjal',
    normalizedName: 'small brinjal',
    aliases: ['chota baingan', 'baby brinjal', 'stuffed brinjal'],
    category: 'Produce',
    subcategory: 'Vegetables',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 6,
    tags: ['vegetable', 'curry'],
  },
  {
    id: 'food-bottle-gourd',
    name: 'Bottle Gourd (Lauki)',
    normalizedName: 'bottle gourd',
    aliases: ['lauki', 'doodhi', 'ghia', 'long melon'],
    category: 'Produce',
    subcategory: 'Vegetables',
    defaultUnit: 'pcs',
    commonUnits: ['pcs', 'kg', 'g'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 8,
    tags: ['vegetable', 'light', 'subzi'],
  },
  {
    id: 'food-bitter-gourd',
    name: 'Bitter Gourd (Karela)',
    normalizedName: 'bitter gourd',
    aliases: ['karela', 'bitter melon'],
    category: 'Produce',
    subcategory: 'Vegetables',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 8,
    tags: ['vegetable', 'healthy'],
  },
  {
    id: 'food-ridge-gourd',
    name: 'Ridge Gourd (Turai)',
    normalizedName: 'ridge gourd',
    aliases: ['turai', 'tori', 'ridge luffa'],
    category: 'Produce',
    subcategory: 'Vegetables',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg', 'pcs'],
    storageType: 'refrigerator',
    perishability: 'high',
    typicalShelfLifeDays: 5,
    tags: ['vegetable', 'light'],
  },
  {
    id: 'food-ivy-gourd',
    name: 'Ivy Gourd (Tindora)',
    normalizedName: 'ivy gourd',
    aliases: ['tindora', 'kundru', 'dondakaya', 'tindli'],
    category: 'Produce',
    subcategory: 'Vegetables',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 7,
    tags: ['vegetable', 'crispy-fry'],
  },
  {
    id: 'food-pointed-gourd',
    name: 'Pointed Gourd (Parwal)',
    normalizedName: 'pointed gourd',
    aliases: ['parwal', 'patol', 'potol'],
    category: 'Produce',
    subcategory: 'Vegetables',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 6,
    tags: ['vegetable', 'curry'],
  },
  {
    id: 'food-french-beans',
    name: 'French Beans',
    normalizedName: 'french bean',
    aliases: ['beans', 'green beans', 'string beans', 'farasbi'],
    category: 'Produce',
    subcategory: 'Vegetables',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 7,
    tags: ['vegetable', 'stir-fry'],
  },
  {
    id: 'food-beetroot',
    name: 'Beetroot',
    normalizedName: 'beetroot',
    aliases: ['chukandar', 'beets', 'red beet'],
    category: 'Produce',
    subcategory: 'Vegetables',
    defaultUnit: 'pcs',
    commonUnits: ['pcs', 'g', 'kg'],
    storageType: 'refrigerator',
    perishability: 'low',
    typicalShelfLifeDays: 18,
    tags: ['salad', 'root', 'healthy'],
  },
  {
    id: 'food-radish',
    name: 'White Radish (Mooli)',
    normalizedName: 'radish',
    aliases: ['mooli', 'mullangi', 'white daikon'],
    category: 'Produce',
    subcategory: 'Vegetables',
    defaultUnit: 'pcs',
    commonUnits: ['pcs', 'g', 'kg'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 8,
    tags: ['salad', 'paratha'],
  },
  {
    id: 'food-sweet-corn',
    name: 'Fresh Sweet Corn',
    normalizedName: 'sweet corn',
    aliases: ['bhutta', 'makka', 'corn cob', 'corn cobs'],
    category: 'Produce',
    subcategory: 'Vegetables',
    defaultUnit: 'pcs',
    commonUnits: ['pcs', 'pack'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 6,
    tags: ['snack', 'vegetable'],
  },
  {
    id: 'food-mushrooms',
    name: 'Button Mushrooms',
    normalizedName: 'mushroom',
    aliases: ['mushroom', 'white button mushroom', 'khumbi'],
    category: 'Produce',
    subcategory: 'Vegetables',
    defaultUnit: 'pack',
    commonUnits: ['pack', 'g'],
    storageType: 'refrigerator',
    perishability: 'high',
    typicalShelfLifeDays: 4,
    tags: ['vegetable', 'protein', 'quick-cook'],
  },
  {
    id: 'food-drumstick',
    name: 'Drumsticks (Moringa)',
    normalizedName: 'drumstick',
    aliases: ['moringa', 'sahjan', 'murungakkai'],
    category: 'Produce',
    subcategory: 'Vegetables',
    defaultUnit: 'pcs',
    commonUnits: ['pcs', 'bunch'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 7,
    tags: ['sambar', 'healthy'],
  },
  {
    id: 'food-raw-banana',
    name: 'Raw Green Banana',
    normalizedName: 'raw banana',
    aliases: ['kaccha kela', 'plantain', 'green banana'],
    category: 'Produce',
    subcategory: 'Vegetables',
    defaultUnit: 'pcs',
    commonUnits: ['pcs', 'kg'],
    storageType: 'pantry',
    perishability: 'medium',
    typicalShelfLifeDays: 8,
    tags: ['vegetable', 'fry'],
  },

  // ==========================================
  // PRODUCE — LEAFY GREENS & HERBS
  // ==========================================
  {
    id: 'food-spinach',
    name: 'Baby Spinach',
    normalizedName: 'spinach',
    aliases: ['palak', 'spinach leaves', 'fresh palak', 'desi palak', 'leafy spinach'],
    category: 'Produce',
    subcategory: 'Leafy Greens',
    defaultUnit: 'g',
    commonUnits: ['g', 'bunch', 'kg'],
    storageType: 'refrigerator',
    perishability: 'high',
    typicalShelfLifeDays: 4,
    tags: ['greens', 'iron', 'palak-paneer', 'healthy'],
    commonUses: ['Palak Paneer', 'Dal Palak', 'Green Smoothies', 'Spinach Omelettes'],
  },
  {
    id: 'food-coriander',
    name: 'Fresh Coriander',
    normalizedName: 'coriander',
    aliases: ['dhaniya', 'cilantro', 'dhaniya patti', 'fresh cilantro', 'kothmir', 'hara dhaniya'],
    category: 'Produce',
    subcategory: 'Herbs',
    defaultUnit: 'bunch',
    commonUnits: ['bunch', 'g'],
    storageType: 'refrigerator',
    perishability: 'high',
    typicalShelfLifeDays: 5,
    tags: ['herb', 'garnish', 'chutney', 'staple'],
    commonUses: ['Green Chutney', 'Dal & Curry Garnish', 'Chaat Dressing', 'Kachumber'],
  },
  {
    id: 'food-mint',
    name: 'Fresh Mint',
    normalizedName: 'mint',
    aliases: ['pudina', 'pudina leaves', 'mint leaves', 'spearmint'],
    category: 'Produce',
    subcategory: 'Herbs',
    defaultUnit: 'bunch',
    commonUnits: ['bunch', 'g'],
    storageType: 'refrigerator',
    perishability: 'high',
    typicalShelfLifeDays: 6,
    tags: ['herb', 'chutney', 'raita', 'beverage'],
    commonUses: ['Mint Chutney', 'Pudina Chaas', 'Biryani Marinade', 'Mojitos & Lemonade'],
  },
  {
    id: 'food-curry-leaves',
    name: 'Curry Leaves',
    normalizedName: 'curry leaf',
    aliases: ['kadi patta', 'meetha neem', 'curry patta', 'karivepaku'],
    category: 'Produce',
    subcategory: 'Herbs',
    defaultUnit: 'bunch',
    commonUnits: ['bunch', 'g', 'pack'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 12,
    tags: ['tadka', 'aromatic', 'south-indian'],
  },
  {
    id: 'food-methi',
    name: 'Fresh Fenugreek Leaves (Methi)',
    normalizedName: 'fenugreek leaf',
    aliases: ['methi', 'fresh methi', 'methi leaves', 'methi saag'],
    category: 'Produce',
    subcategory: 'Leafy Greens',
    defaultUnit: 'bunch',
    commonUnits: ['bunch', 'g'],
    storageType: 'refrigerator',
    perishability: 'high',
    typicalShelfLifeDays: 4,
    tags: ['greens', 'paratha', 'winter-greens'],
  },
  {
    id: 'food-sarson',
    name: 'Mustard Greens (Sarson)',
    normalizedName: 'mustard green',
    aliases: ['sarson saag', 'mustard leaves', 'sarson ka saag'],
    category: 'Produce',
    subcategory: 'Leafy Greens',
    defaultUnit: 'bunch',
    commonUnits: ['bunch', 'kg'],
    storageType: 'refrigerator',
    perishability: 'high',
    typicalShelfLifeDays: 4,
    tags: ['greens', 'punjabi', 'seasonal'],
  },

  // ==========================================
  // PRODUCE — FRUITS
  // ==========================================
  {
    id: 'food-apple',
    name: 'Crisp Apples',
    normalizedName: 'apple',
    aliases: ['seb', 'shimla apple', 'kashmir apple', 'royal delicious apple', 'apples'],
    category: 'Produce',
    subcategory: 'Fruits',
    defaultUnit: 'kg',
    commonUnits: ['kg', 'pcs'],
    storageType: 'refrigerator',
    perishability: 'low',
    typicalShelfLifeDays: 18,
    tags: ['fruit', 'snack', 'fiber'],
  },
  {
    id: 'food-banana',
    name: 'Ripe Bananas',
    normalizedName: 'banana',
    aliases: ['kela', 'robusta banana', 'elaichi kela', 'bananas'],
    category: 'Produce',
    subcategory: 'Fruits',
    defaultUnit: 'pcs',
    commonUnits: ['pcs', 'dozen', 'kg'],
    storageType: 'countertop',
    perishability: 'high',
    typicalShelfLifeDays: 5,
    tags: ['fruit', 'energy', 'breakfast'],
  },
  {
    id: 'food-pomegranate',
    name: 'Pomegranate (Anaar)',
    normalizedName: 'pomegranate',
    aliases: ['anaar', 'anar', 'pomegranates'],
    category: 'Produce',
    subcategory: 'Fruits',
    defaultUnit: 'pcs',
    commonUnits: ['pcs', 'kg'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 14,
    tags: ['fruit', 'antioxidant', 'salad'],
  },
  {
    id: 'food-papaya',
    name: 'Ripe Papaya',
    normalizedName: 'papaya',
    aliases: ['papita', 'red lady papaya'],
    category: 'Produce',
    subcategory: 'Fruits',
    defaultUnit: 'pcs',
    commonUnits: ['pcs', 'kg'],
    storageType: 'refrigerator',
    perishability: 'high',
    typicalShelfLifeDays: 5,
    tags: ['fruit', 'digestive'],
  },
  {
    id: 'food-orange',
    name: 'Nagpur Oranges',
    normalizedName: 'orange',
    aliases: ['santre', 'santra', 'nagpur orange', 'mandarin'],
    category: 'Produce',
    subcategory: 'Fruits',
    defaultUnit: 'kg',
    commonUnits: ['kg', 'pcs'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 10,
    tags: ['fruit', 'citrus', 'vitamin-c'],
  },
  {
    id: 'food-mango',
    name: 'Alphonso Mangoes',
    normalizedName: 'mango',
    aliases: ['aam', 'alphonso', 'kesar mango', 'safeda'],
    category: 'Produce',
    subcategory: 'Fruits',
    defaultUnit: 'kg',
    commonUnits: ['kg', 'pcs', 'dozen'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 6,
    tags: ['fruit', 'seasonal', 'sweet'],
  },

  // ==========================================
  // DAIRY & EGGS
  // ==========================================
  {
    id: 'food-milk-cow',
    name: 'Fresh Cow Milk',
    normalizedName: 'milk',
    aliases: ['doodh', 'fresh milk', 'toned milk', 'full cream milk', 'cow milk', 'pasteurized milk'],
    category: 'Dairy & Eggs',
    subcategory: 'Milk',
    defaultUnit: 'L',
    commonUnits: ['L', 'ml', 'pack'],
    storageType: 'refrigerator',
    perishability: 'high',
    typicalShelfLifeDays: 3,
    tags: ['dairy', 'calcium', 'chai', 'daily-staple'],
    commonUses: ['Morning Chai / Coffee', 'Oatmeal & Porridge', 'Cereal', 'Baking'],
  },
  {
    id: 'food-milk-soy',
    name: 'Unsweetened Soy Milk',
    normalizedName: 'soy milk',
    aliases: ['soya milk', 'plant milk', 'soy drink'],
    category: 'Dairy & Eggs',
    subcategory: 'Plant Alternatives',
    defaultUnit: 'L',
    commonUnits: ['L', 'ml', 'pack'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 10,
    tags: ['vegan', 'plant-milk', 'lactose-free', 'protein'],
    commonUses: ['Vegan Chai / Latte', 'Protein Shakes', 'Cereal', 'Baking'],
  },
  {
    id: 'food-milk-almond',
    name: 'Almond Milk',
    normalizedName: 'almond milk',
    aliases: ['badam milk alternative', 'unsweetened almond milk'],
    category: 'Dairy & Eggs',
    subcategory: 'Plant Alternatives',
    defaultUnit: 'L',
    commonUnits: ['L', 'ml', 'pack'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 10,
    tags: ['vegan', 'plant-milk', 'low-calorie', 'dairy-free'],
    commonUses: ['Overnight Oats', 'Smoothies', 'Specialty Coffee', 'Desserts'],
  },
  {
    id: 'food-milk-oat',
    name: 'Oat Milk Barista',
    normalizedName: 'oat milk',
    aliases: ['oat drink', 'barista oat milk'],
    category: 'Dairy & Eggs',
    subcategory: 'Plant Alternatives',
    defaultUnit: 'L',
    commonUnits: ['L', 'ml', 'pack'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 10,
    tags: ['vegan', 'plant-milk', 'creamy', 'coffee'],
    commonUses: ['Lattes & Coffee', 'Matcha Drinks', 'Oat Porridge', 'Pancakes'],
  },
  {
    id: 'food-paneer',
    name: 'Malai Paneer',
    normalizedName: 'paneer',
    aliases: ['fresh paneer', 'cottage cheese', 'paneer block', 'chena', 'soft paneer'],
    category: 'Dairy & Eggs',
    subcategory: 'Paneer',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg', 'pack'],
    storageType: 'refrigerator',
    perishability: 'high',
    typicalShelfLifeDays: 5,
    tags: ['dairy', 'protein', 'vegetarian', 'subzi'],
    commonUses: ['Palak Paneer', 'Paneer Butter Masala', 'Paneer Bhurji', 'Tikka Skewers'],
  },
  {
    id: 'food-paneer-lowfat',
    name: 'Low-Fat Paneer',
    normalizedName: 'low fat paneer',
    aliases: ['diet paneer', 'skimmed milk paneer', 'fit paneer'],
    category: 'Dairy & Eggs',
    subcategory: 'Paneer',
    defaultUnit: 'g',
    commonUnits: ['g', 'pack'],
    storageType: 'refrigerator',
    perishability: 'high',
    typicalShelfLifeDays: 5,
    tags: ['dairy', 'high-protein', 'low-fat', 'diet'],
    commonUses: ['High-Protein Salads', 'Paneer Bhurji', 'Fitness Wraps'],
  },
  {
    id: 'food-tofu',
    name: 'Firm Tofu',
    normalizedName: 'tofu',
    aliases: ['soy paneer', 'bean curd', 'firm soy block'],
    category: 'Dairy & Eggs',
    subcategory: 'Plant Alternatives',
    defaultUnit: 'g',
    commonUnits: ['g', 'pack'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 14,
    tags: ['vegan', 'protein', 'stir-fry', 'plant-based'],
    commonUses: ['Stir-fries', 'Vegan Curries', 'Air-fried Tofu Bowls'],
  },
  {
    id: 'food-curd',
    name: 'Fresh Curd / Dahi',
    normalizedName: 'curd',
    aliases: ['dahi', 'fresh dahi', 'plain curd', 'thick curd', 'desi dahi'],
    category: 'Dairy & Eggs',
    subcategory: 'Curd & Yogurt',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg', 'pack'],
    storageType: 'refrigerator',
    perishability: 'high',
    typicalShelfLifeDays: 6,
    tags: ['dairy', 'probiotic', 'lunch', 'daily-staple'],
    commonUses: ['Boondi Raita', 'Dahi Tadka', 'Curd Rice', 'Chaas'],
  },
  {
    id: 'food-greek-yogurt',
    name: 'Greek Yogurt',
    normalizedName: 'greek yogurt',
    aliases: ['strained yogurt', 'epigamia', 'thick yogurt', 'high protein yogurt'],
    category: 'Dairy & Eggs',
    subcategory: 'Curd & Yogurt',
    defaultUnit: 'g',
    commonUnits: ['g', 'cup', 'pack'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 14,
    tags: ['dairy', 'protein', 'breakfast', 'smoothies'],
    commonUses: ['Breakfast Bowls', 'Berry Smoothies', 'Protein Parfaits', 'Herbed Dips'],
  },
  {
    id: 'food-hung-curd',
    name: 'Hung Curd / Chakka',
    normalizedName: 'hung curd',
    aliases: ['chakka', 'strained dahi', 'shrikhand base'],
    category: 'Dairy & Eggs',
    subcategory: 'Curd & Yogurt',
    defaultUnit: 'g',
    commonUnits: ['g', 'pack'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 7,
    tags: ['dairy', 'marination', 'tikka', 'shrikhand'],
    commonUses: ['Tandoori Marinade', 'Shrikhand', 'Sandwich Spreads', 'Dips'],
  },
  {
    id: 'food-butter',
    name: 'Salted Dairy Butter',
    normalizedName: 'butter',
    aliases: ['amul butter', 'salted butter', 'makhan', 'table butter', 'dairy butter'],
    category: 'Dairy & Eggs',
    subcategory: 'Butter',
    defaultUnit: 'g',
    commonUnits: ['g', 'pack'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 30,
    tags: ['dairy', 'toast', 'paratha'],
  },
  {
    id: 'food-ghee',
    name: 'Desi Cow Ghee',
    normalizedName: 'ghee',
    aliases: ['pure ghee', 'desi ghee', 'clarified butter', 'cow ghee'],
    category: 'Dairy & Eggs',
    subcategory: 'Ghee',
    defaultUnit: 'ml',
    commonUnits: ['ml', 'L', 'g', 'kg'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 180,
    tags: ['staple', 'cooking-fat', 'ayurvedic', 'tadka'],
  },
  {
    id: 'food-cream',
    name: 'Fresh Cooking Cream',
    normalizedName: 'cream',
    aliases: ['malai', 'fresh cream', 'cooking cream', 'whipping cream', 'heavy cream'],
    category: 'Dairy & Eggs',
    subcategory: 'Cream',
    defaultUnit: 'ml',
    commonUnits: ['ml', 'pack'],
    storageType: 'refrigerator',
    perishability: 'high',
    typicalShelfLifeDays: 5,
    tags: ['dairy', 'curry-rich', 'dessert'],
  },
  {
    id: 'food-cheese-slices',
    name: 'Processed Cheese Slices',
    normalizedName: 'cheese slice',
    aliases: ['cheese', 'cheddar cheese', 'amul cheese', 'cheese slices', 'cheese cubes'],
    category: 'Dairy & Eggs',
    subcategory: 'Cheese',
    defaultUnit: 'pack',
    commonUnits: ['pack', 'g', 'pcs'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 45,
    tags: ['dairy', 'sandwich', 'snack'],
  },
  {
    id: 'food-eggs',
    name: 'Farm Fresh Eggs',
    normalizedName: 'egg',
    aliases: ['ande', 'poultry eggs', 'brown eggs', 'white eggs', 'farm eggs'],
    category: 'Dairy & Eggs',
    subcategory: 'Eggs',
    defaultUnit: 'pcs',
    commonUnits: ['pcs', 'pack', 'dozen'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 21,
    tags: ['protein', 'breakfast', 'versatile'],
  },

  // ==========================================
  // GRAINS, FLOURS & STAPLES
  // ==========================================
  {
    id: 'food-atta',
    name: 'Chakki Wholewheat Atta',
    normalizedName: 'atta',
    aliases: ['gehu ka atta', 'wheat flour', 'whole wheat flour', 'sharbati atta', 'chapatis flour'],
    category: 'Pantry & Grains',
    subcategory: 'Flours',
    defaultUnit: 'kg',
    commonUnits: ['kg', 'g', 'pack'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 90,
    tags: ['grain', 'roti', 'staple', 'daily-staple'],
  },
  {
    id: 'food-maida',
    name: 'All Purpose Flour (Maida)',
    normalizedName: 'maida',
    aliases: ['refined flour', 'white flour', 'all purpose flour'],
    category: 'Pantry & Grains',
    subcategory: 'Flours',
    defaultUnit: 'kg',
    commonUnits: ['kg', 'g'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 120,
    tags: ['baking', 'snack'],
  },
  {
    id: 'food-besan',
    name: 'Gram Flour (Besan)',
    normalizedName: 'besan',
    aliases: ['chana atta', 'chickpea flour', 'bengal gram flour'],
    category: 'Pantry & Grains',
    subcategory: 'Flours',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 90,
    tags: ['protein', 'pakoda', 'cheela', 'kadhi'],
  },
  {
    id: 'food-suji',
    name: 'Semolina (Suji / Rava)',
    normalizedName: 'suji',
    aliases: ['rava', 'semolina', 'sooji', 'bombay rava'],
    category: 'Pantry & Grains',
    subcategory: 'Flours',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 90,
    tags: ['upma', 'halwa', 'breakfast'],
  },
  {
    id: 'food-poha',
    name: 'Thick Poha (Flattened Rice)',
    normalizedName: 'poha',
    aliases: ['flattened rice', 'aval', 'chiwda', 'powa', 'avalakki'],
    category: 'Pantry & Grains',
    subcategory: 'Flakes & Cereals',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg', 'pack'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 90,
    tags: ['breakfast', 'quick-cook', 'snack'],
  },
  {
    id: 'food-basmati-rice',
    name: 'Premium Basmati Rice',
    normalizedName: 'basmati rice',
    aliases: ['chawal', 'biryani rice', 'long grain rice', 'aged basmati', 'daawat basmati'],
    category: 'Pantry & Grains',
    subcategory: 'Rice',
    defaultUnit: 'kg',
    commonUnits: ['kg', 'g', 'pack'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 365,
    tags: ['rice', 'biryani', 'staple'],
  },
  {
    id: 'food-sona-masoori-rice',
    name: 'Sona Masoori Rice',
    normalizedName: 'sona masoori rice',
    aliases: ['daily rice', 'white rice', 'raw rice', 'table rice'],
    category: 'Pantry & Grains',
    subcategory: 'Rice',
    defaultUnit: 'kg',
    commonUnits: ['kg', 'g'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 365,
    tags: ['rice', 'daily-staple'],
  },
  {
    id: 'food-rolled-oats',
    name: 'Rolled Oats',
    normalizedName: 'oats',
    aliases: ['quaker oats', 'instant oats', 'breakfast oats', 'oatmeal'],
    category: 'Pantry & Grains',
    subcategory: 'Flakes & Cereals',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg', 'pack'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 180,
    tags: ['fiber', 'breakfast', 'healthy'],
  },
  {
    id: 'food-pasta-penne',
    name: 'Durum Wheat Penne Pasta',
    normalizedName: 'penne pasta',
    aliases: ['pasta', 'penne', 'macaroni', 'wheat pasta'],
    category: 'Pantry & Grains',
    subcategory: 'Pasta & Noodles',
    defaultUnit: 'g',
    commonUnits: ['g', 'pack'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 365,
    tags: ['italian', 'dinner', 'quick-meal'],
  },
  {
    id: 'food-noodles',
    name: 'Hakka Noodles',
    normalizedName: 'noodle',
    aliases: ['chowmein', 'egg noodles', 'veg noodles', 'instant noodles', 'maggi'],
    category: 'Pantry & Grains',
    subcategory: 'Pasta & Noodles',
    defaultUnit: 'pack',
    commonUnits: ['pack', 'g'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 180,
    tags: ['snack', 'asian'],
  },
  {
    id: 'food-sabudana',
    name: 'Sabudana (Tapioca Sago)',
    normalizedName: 'sabudana',
    aliases: ['sago', 'tapioca pearls', 'javvarisi'],
    category: 'Pantry & Grains',
    subcategory: 'Grains',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 180,
    tags: ['fasting', 'khichdi'],
  },

  // ==========================================
  // PULSES & LEGUMES (DALS)
  // ==========================================
  {
    id: 'food-toor-dal',
    name: 'Arhar / Toor Dal',
    normalizedName: 'toor dal',
    aliases: ['arhar dal', 'yellow pigeon peas', 'tuvar dal', 'toor dal unpolished'],
    category: 'Pantry & Grains',
    subcategory: 'Pulses & Legumes',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg', 'pack'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 180,
    tags: ['dal', 'protein', 'sambar', 'daily-staple'],
  },
  {
    id: 'food-moong-dal',
    name: 'Yellow Moong Dal (Split)',
    normalizedName: 'moong dal',
    aliases: ['dhuli moong', 'yellow lentils', 'moong dal split', 'moong'],
    category: 'Pantry & Grains',
    subcategory: 'Pulses & Legumes',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 180,
    tags: ['dal', 'protein', 'khichdi', 'light'],
  },
  {
    id: 'food-chana-dal',
    name: 'Chana Dal (Bengal Gram)',
    normalizedName: 'chana dal',
    aliases: ['bengal gram split', 'chana dal unpolished', 'split chickpeas'],
    category: 'Pantry & Grains',
    subcategory: 'Pulses & Legumes',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 180,
    tags: ['dal', 'tadka', 'vada'],
  },
  {
    id: 'food-masoor-dal',
    name: 'Red Masoor Dal (Split)',
    normalizedName: 'masoor dal',
    aliases: ['lal masoor', 'red lentils', 'split red lentils'],
    category: 'Pantry & Grains',
    subcategory: 'Pulses & Legumes',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 180,
    tags: ['dal', 'quick-cook'],
  },
  {
    id: 'food-urad-dal',
    name: 'Urad Dal (White Split / Dhuli)',
    normalizedName: 'urad dal',
    aliases: ['white urad', 'dhuli urad', 'idli dal', 'split black gram'],
    category: 'Pantry & Grains',
    subcategory: 'Pulses & Legumes',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 180,
    tags: ['idli', 'dosa', 'dal-makhani'],
  },
  {
    id: 'food-rajma',
    name: 'Kashmiri Rajma (Kidney Beans)',
    normalizedName: 'rajma',
    aliases: ['kidney beans', 'chitra rajma', 'red kidney beans'],
    category: 'Pantry & Grains',
    subcategory: 'Pulses & Legumes',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 240,
    tags: ['protein', 'punjabi', 'rajma-chawal'],
  },
  {
    id: 'food-kabuli-chana',
    name: 'Kabuli Chana (White Chickpeas)',
    normalizedName: 'kabuli chana',
    aliases: ['chole', 'white chickpeas', 'garbanzo beans', 'chana'],
    category: 'Pantry & Grains',
    subcategory: 'Pulses & Legumes',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 240,
    tags: ['chole', 'protein', 'bhature'],
  },
  {
    id: 'food-kala-chana',
    name: 'Kala Chana (Brown Chickpeas)',
    normalizedName: 'kala chana',
    aliases: ['black chickpeas', 'desi chana', 'chana brown'],
    category: 'Pantry & Grains',
    subcategory: 'Pulses & Legumes',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 240,
    tags: ['iron', 'protein', 'boiled-chana'],
  },

  // ==========================================
  // SPICES & SEASONINGS
  // ==========================================
  {
    id: 'food-turmeric',
    name: 'Pure Turmeric Powder (Haldi)',
    normalizedName: 'turmeric',
    aliases: ['haldi', 'turmeric powder', 'haldi powder', 'ground turmeric'],
    category: 'Spices & Condiments',
    subcategory: 'Ground Spices',
    defaultUnit: 'g',
    commonUnits: ['g', 'pack'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 365,
    tags: ['spice', 'essential', 'antiseptic', 'daily-staple'],
  },
  {
    id: 'food-red-chilli-powder',
    name: 'Red Chilli Powder',
    normalizedName: 'red chilli powder',
    aliases: ['lal mirch', 'mirchi powder', 'kashmiri lal mirch', 'deglet mirch'],
    category: 'Spices & Condiments',
    subcategory: 'Ground Spices',
    defaultUnit: 'g',
    commonUnits: ['g', 'pack'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 300,
    tags: ['spice', 'essential', 'heat', 'daily-staple'],
  },
  {
    id: 'food-cumin-seeds',
    name: 'Cumin Seeds (Jeera)',
    normalizedName: 'cumin seed',
    aliases: ['jeera', 'whole cumin', 'cumin', 'zeera'],
    category: 'Spices & Condiments',
    subcategory: 'Whole Spices',
    defaultUnit: 'g',
    commonUnits: ['g', 'pack'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 365,
    tags: ['tadka', 'essential', 'daily-staple'],
  },
  {
    id: 'food-coriander-powder',
    name: 'Coriander Powder (Dhaniya Powder)',
    normalizedName: 'coriander powder',
    aliases: ['dhaniya powder', 'ground coriander', 'dhania powder'],
    category: 'Spices & Condiments',
    subcategory: 'Ground Spices',
    defaultUnit: 'g',
    commonUnits: ['g', 'pack'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 300,
    tags: ['spice', 'essential', 'gravy-thickener', 'daily-staple'],
  },
  {
    id: 'food-garam-masala',
    name: 'Royal Garam Masala',
    normalizedName: 'garam masala',
    aliases: ['garam masala powder', 'spice mix', 'kitchen king'],
    category: 'Spices & Condiments',
    subcategory: 'Spice Blends',
    defaultUnit: 'g',
    commonUnits: ['g', 'pack'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 240,
    tags: ['spice', 'finishing', 'aromatic'],
  },
  {
    id: 'food-mustard-seeds',
    name: 'Mustard Seeds (Rai / Sarson)',
    normalizedName: 'mustard seed',
    aliases: ['rai', 'sarson seeds', 'black mustard seeds', 'yellow mustard'],
    category: 'Spices & Condiments',
    subcategory: 'Whole Spices',
    defaultUnit: 'g',
    commonUnits: ['g', 'pack'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 365,
    tags: ['tadka', 'south-indian', 'pickle'],
  },
  {
    id: 'food-black-pepper',
    name: 'Whole Black Peppercorns',
    normalizedName: 'black pepper',
    aliases: ['kali mirch', 'black pepper', 'ground black pepper', 'peppercorns'],
    category: 'Spices & Condiments',
    subcategory: 'Whole Spices',
    defaultUnit: 'g',
    commonUnits: ['g', 'pack'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 365,
    tags: ['spice', 'pungent', 'kadha'],
  },
  {
    id: 'food-cardamom',
    name: 'Green Cardamom (Elaichi)',
    normalizedName: 'green cardamom',
    aliases: ['elaichi', 'choti elaichi', 'cardamom pods'],
    category: 'Spices & Condiments',
    subcategory: 'Whole Spices',
    defaultUnit: 'g',
    commonUnits: ['g', 'pack'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 365,
    tags: ['sweet', 'tea', 'biryani'],
  },
  {
    id: 'food-cinnamon',
    name: 'Cinnamon Sticks (Dalchini)',
    normalizedName: 'cinnamon',
    aliases: ['dalchini', 'cinnamon quills', 'cassia bark'],
    category: 'Spices & Condiments',
    subcategory: 'Whole Spices',
    defaultUnit: 'g',
    commonUnits: ['g', 'pack'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 365,
    tags: ['spice', 'warm', 'biryani'],
  },
  {
    id: 'food-cloves',
    name: 'Cloves (Laung)',
    normalizedName: 'clove',
    aliases: ['laung', 'lavang', 'whole cloves'],
    category: 'Spices & Condiments',
    subcategory: 'Whole Spices',
    defaultUnit: 'g',
    commonUnits: ['g', 'pack'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 365,
    tags: ['spice', 'aromatic', 'chai'],
  },
  {
    id: 'food-kasuri-methi',
    name: 'Kasuri Methi (Dried Fenugreek)',
    normalizedName: 'kasuri methi',
    aliases: ['dried methi', 'kasoori methi', 'dry fenugreek leaves'],
    category: 'Spices & Condiments',
    subcategory: 'Herbs',
    defaultUnit: 'g',
    commonUnits: ['g', 'pack'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 180,
    tags: ['herb', 'finishing', 'butter-chicken', 'paneer'],
  },
  {
    id: 'food-hing',
    name: 'Asafoetida (Hing)',
    normalizedName: 'asafoetida',
    aliases: ['hing', 'compounded asafoetida', 'heeng'],
    category: 'Spices & Condiments',
    subcategory: 'Ground Spices',
    defaultUnit: 'g',
    commonUnits: ['g', 'pcs'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 365,
    tags: ['digestive', 'tadka', 'dal'],
  },
  {
    id: 'food-salt',
    name: 'Iodized Table Salt',
    normalizedName: 'salt',
    aliases: ['namak', 'tata salt', 'sea salt', 'iodized salt'],
    category: 'Spices & Condiments',
    subcategory: 'Seasoning',
    defaultUnit: 'kg',
    commonUnits: ['kg', 'g', 'pack'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 730,
    tags: ['essential', 'daily-staple'],
  },
  {
    id: 'food-sugar',
    name: 'Refined White Sugar',
    normalizedName: 'sugar',
    aliases: ['cheeni', 'shakkar', 'crystal sugar', 'granulated sugar'],
    category: 'Spices & Condiments',
    subcategory: 'Sweeteners',
    defaultUnit: 'kg',
    commonUnits: ['kg', 'g'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 730,
    tags: ['sweet', 'tea', 'daily-staple'],
  },
  {
    id: 'food-jaggery',
    name: 'Organic Jaggery (Gud)',
    normalizedName: 'jaggery',
    aliases: ['gud', 'gur', 'jaggery powder', 'palm jaggery', 'bhel gud'],
    category: 'Spices & Condiments',
    subcategory: 'Sweeteners',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg'],
    storageType: 'pantry',
    perishability: 'medium',
    typicalShelfLifeDays: 180,
    tags: ['natural-sweetener', 'winter', 'iron'],
  },

  // ==========================================
  // OILS & CONDIMENTS
  // ==========================================
  {
    id: 'food-mustard-oil',
    name: 'Kachi Ghani Mustard Oil',
    normalizedName: 'mustard oil',
    aliases: ['sarson ka tel', 'cold pressed mustard oil', 'pungent oil'],
    category: 'Spices & Condiments',
    subcategory: 'Cooking Oils',
    defaultUnit: 'L',
    commonUnits: ['L', 'ml'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 365,
    tags: ['cooking-oil', 'pickling', 'north-indian'],
  },
  {
    id: 'food-sunflower-oil',
    name: 'Refined Sunflower Cooking Oil',
    normalizedName: 'sunflower oil',
    aliases: ['cooking oil', 'vegetable oil', 'refined oil', 'fortune oil'],
    category: 'Spices & Condiments',
    subcategory: 'Cooking Oils',
    defaultUnit: 'L',
    commonUnits: ['L', 'ml'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 270,
    tags: ['cooking-oil', 'neutral', 'daily-staple'],
  },
  {
    id: 'food-olive-oil',
    name: 'Extra Virgin Olive Oil',
    normalizedName: 'olive oil',
    aliases: ['evoo', 'pure olive oil', 'pomace olive oil', 'salad oil'],
    category: 'Spices & Condiments',
    subcategory: 'Cooking Oils',
    defaultUnit: 'ml',
    commonUnits: ['ml', 'L'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 365,
    tags: ['healthy', 'salad', 'pasta'],
  },
  {
    id: 'food-tomato-ketchup',
    name: 'Tomato Ketchup',
    normalizedName: 'tomato ketchup',
    aliases: ['ketchup', 'tomato sauce', 'maggi sauce', 'kissan ketchup'],
    category: 'Spices & Condiments',
    subcategory: 'Sauces',
    defaultUnit: 'g',
    commonUnits: ['g', 'ml', 'bottle'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 120,
    tags: ['condiment', 'snack', 'kids'],
  },
  {
    id: 'food-soy-sauce',
    name: 'Dark Soy Sauce',
    normalizedName: 'soy sauce',
    aliases: ['soya sauce', 'light soy sauce', 'ching soy sauce'],
    category: 'Spices & Condiments',
    subcategory: 'Sauces',
    defaultUnit: 'ml',
    commonUnits: ['ml', 'bottle'],
    storageType: 'refrigerator',
    perishability: 'low',
    typicalShelfLifeDays: 240,
    tags: ['chinese', 'stir-fry', 'noodles'],
  },
  {
    id: 'food-vinegar',
    name: 'White Synthetic Vinegar',
    normalizedName: 'vinegar',
    aliases: ['sirka', 'white vinegar', 'cooking vinegar', 'apple cider vinegar'],
    category: 'Spices & Condiments',
    subcategory: 'Sauces',
    defaultUnit: 'ml',
    commonUnits: ['ml', 'L'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 730,
    tags: ['acidic', 'chinese', 'preservative'],
  },
  {
    id: 'food-mango-pickle',
    name: 'Traditional Mango Pickle',
    normalizedName: 'mango pickle',
    aliases: ['aam ka achar', 'mango achar', 'spicy pickle', 'mother recipe pickle'],
    category: 'Spices & Condiments',
    subcategory: 'Pickles',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg', 'jar'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 365,
    tags: ['pickle', 'spicy', 'paratha'],
  },

  // ==========================================
  // BAKERY & BREAD
  // ==========================================
  {
    id: 'food-bread-wheat',
    name: 'Wholewheat Bread Loaf',
    normalizedName: 'wholewheat bread',
    aliases: ['brown bread', 'wheat bread', 'sandwich bread', 'bread loaf', 'atta bread'],
    category: 'Bakery',
    subcategory: 'Bread',
    defaultUnit: 'loaf',
    commonUnits: ['loaf', 'pcs', 'pack'],
    storageType: 'countertop',
    perishability: 'high',
    typicalShelfLifeDays: 5,
    tags: ['breakfast', 'sandwich', 'daily-staple'],
  },
  {
    id: 'food-bread-white',
    name: 'White Sandwich Bread',
    normalizedName: 'white bread',
    aliases: ['milk bread', 'white loaf', 'sandwich bread white'],
    category: 'Bakery',
    subcategory: 'Bread',
    defaultUnit: 'loaf',
    commonUnits: ['loaf', 'pack'],
    storageType: 'countertop',
    perishability: 'high',
    typicalShelfLifeDays: 4,
    tags: ['breakfast', 'sandwich'],
  },
  {
    id: 'food-pav',
    name: 'Fresh Ladi Pav',
    normalizedName: 'pav',
    aliases: ['ladi pav', 'pav buns', 'bun', 'vada pav bread', 'misal pav bread'],
    category: 'Bakery',
    subcategory: 'Buns',
    defaultUnit: 'pack',
    commonUnits: ['pack', 'pcs'],
    storageType: 'countertop',
    perishability: 'high',
    typicalShelfLifeDays: 3,
    tags: ['snack', 'street-food', 'pav-bhaji'],
  },

  // ==========================================
  // BEVERAGES
  // ==========================================
  {
    id: 'food-tea-ctc',
    name: 'Assam CTC Leaf Tea',
    normalizedName: 'tea',
    aliases: ['chai patti', 'black tea', 'tea leaves', 'wagh bakri', 'red label', 'tata tea'],
    category: 'Beverages',
    subcategory: 'Tea',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg', 'pack'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 365,
    tags: ['chai', 'hot-beverage', 'daily-staple'],
  },
  {
    id: 'food-coffee-instant',
    name: 'Classic Instant Coffee',
    normalizedName: 'coffee',
    aliases: ['nescafe', 'bru', 'coffee powder', 'instant coffee', 'filter coffee powder'],
    category: 'Beverages',
    subcategory: 'Coffee',
    defaultUnit: 'g',
    commonUnits: ['g', 'jar', 'pack'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 365,
    tags: ['caffeine', 'beverage', 'daily-staple'],
  },
  {
    id: 'food-green-tea',
    name: 'Organic Green Tea Bags',
    normalizedName: 'green tea',
    aliases: ['green tea', 'herbal tea', 'tulsi green tea', 'lemon green tea'],
    category: 'Beverages',
    subcategory: 'Tea',
    defaultUnit: 'pack',
    commonUnits: ['pack', 'pcs'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 365,
    tags: ['healthy', 'antioxidant'],
  },

  // ==========================================
  // NUTS, SEEDS & DRY FRUITS
  // ==========================================
  {
    id: 'food-almonds',
    name: 'California Almonds (Badam)',
    normalizedName: 'almond',
    aliases: ['badam', 'raw almonds', 'whole almonds'],
    category: 'Pantry & Grains',
    subcategory: 'Nuts & Seeds',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg', 'pack'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 180,
    tags: ['dry-fruit', 'healthy-fat', 'brain-food'],
  },
  {
    id: 'food-cashews',
    name: 'Whole Cashew Nuts (Kaju)',
    normalizedName: 'cashew',
    aliases: ['kaju', 'raw cashews', 'cashew nuts', 'kaju tukda'],
    category: 'Pantry & Grains',
    subcategory: 'Nuts & Seeds',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg', 'pack'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 180,
    tags: ['dry-fruit', 'curry-gravy', 'sweet'],
  },
  {
    id: 'food-walnuts',
    name: 'Walnut Kernels (Akhrot)',
    normalizedName: 'walnut',
    aliases: ['akhrot', 'walnuts', 'kashmiri akhrot'],
    category: 'Pantry & Grains',
    subcategory: 'Nuts & Seeds',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg'],
    storageType: 'refrigerator',
    perishability: 'medium',
    typicalShelfLifeDays: 120,
    tags: ['omega-3', 'dry-fruit'],
  },
  {
    id: 'food-raisins',
    name: 'Golden Raisins (Kishmish)',
    normalizedName: 'raisin',
    aliases: ['kishmish', 'kismis', 'sultanas', 'dry grapes'],
    category: 'Pantry & Grains',
    subcategory: 'Dry Fruits',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 180,
    tags: ['kheer', 'sweet', 'iron'],
  },
  {
    id: 'food-makhana',
    name: 'Fox Nuts (Makhana)',
    normalizedName: 'makhana',
    aliases: ['lotus seeds', 'phool makhana', 'puffed lotus seeds'],
    category: 'Pantry & Grains',
    subcategory: 'Snacks',
    defaultUnit: 'g',
    commonUnits: ['g', 'pack'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 180,
    tags: ['snack', 'calcium', 'roasted-makhana'],
  },
  {
    id: 'food-peanuts',
    name: 'Raw Peanuts (Moongphali)',
    normalizedName: 'peanut',
    aliases: ['moongphali', 'singdana', 'groundnuts', 'raw groundnut'],
    category: 'Pantry & Grains',
    subcategory: 'Nuts & Seeds',
    defaultUnit: 'g',
    commonUnits: ['g', 'kg'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 180,
    tags: ['poha', 'chutney', 'protein'],
  },

  // ==========================================
  // SNACKS & PACKAGED STAPLES
  // ==========================================
  {
    id: 'food-biscuit-marie',
    name: 'Marie Gold Tea Biscuits',
    normalizedName: 'marie biscuit',
    aliases: ['marie biscuit', 'tea biscuits', 'digestive biscuit', 'parle-g'],
    category: 'Pantry & Grains',
    subcategory: 'Biscuits',
    defaultUnit: 'pack',
    commonUnits: ['pack'],
    storageType: 'pantry',
    perishability: 'low',
    typicalShelfLifeDays: 180,
    tags: ['snack', 'tea-time'],
  },
  {
    id: 'food-bhujia',
    name: 'Bikaneri Aloo Bhujia',
    normalizedName: 'bhujia',
    aliases: ['namkeen', 'aloo bhujia', 'sev', 'haldiram bhujia'],
    category: 'Pantry & Grains',
    subcategory: 'Snacks',
    defaultUnit: 'g',
    commonUnits: ['g', 'pack'],
    storageType: 'pantry',
    perishability: 'medium',
    typicalShelfLifeDays: 90,
    tags: ['snack', 'crispy'],
  },
  {
    id: 'food-frozen-peas',
    name: 'Frozen Green Peas',
    normalizedName: 'frozen green pea',
    aliases: ['frozen matar', 'safal peas', 'frozen peas'],
    category: 'Frozen',
    subcategory: 'Frozen Vegetables',
    defaultUnit: 'pack',
    commonUnits: ['pack', 'g', 'kg'],
    storageType: 'freezer',
    perishability: 'low',
    typicalShelfLifeDays: 180,
    tags: ['frozen', 'quick-cook'],
  },
  {
    id: 'food-frozen-corn',
    name: 'Frozen Sweet Corn Kernels',
    normalizedName: 'frozen corn',
    aliases: ['frozen corn', 'safal corn', 'american sweet corn'],
    category: 'Frozen',
    subcategory: 'Frozen Vegetables',
    defaultUnit: 'pack',
    commonUnits: ['pack', 'g'],
    storageType: 'freezer',
    perishability: 'low',
    typicalShelfLifeDays: 180,
    tags: ['frozen', 'sweet-corn'],
  },
];
